name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.publish-local-package.outputs.package }}
    steps:
      - uses: tatethurston/github-actions/publish-local-package@main
        id: publish-local-package
        with:
          path: packages/eslint-plugin-react-prefer-function-component
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: tatethurston/github-actions/test@main
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
